name: Test GitHub Stats Action

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run GitHub Stats Action
        uses: thanhhaudev/github-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_RANGE: "all_time"
          WAKATIME_DATA: "EDITORS,LANGUAGES,OPERATING_SYSTEMS"
          SHOW_METRICS: "COMMIT_TIME_OF_DAY,WAKATIME_SPENT_TIME,LANGUAGE_PER_REPO,COMMIT_DAYS_OF_WEEK"
          TIME_ZONE: "Asia/Ho_Chi_Minh"
          TIME_LAYOUT: "2006-01-02 15:04:05"
          SHOW_LAST_UPDATE: "true"
          ONLY_MAIN_BRANCH: "true"
